name: Report Inactive Location
description: Let maintainers know a listed location is closed, moved, or no longer active
title: "Report Inactive: [Location Name]"
labels: data-maintenance, location-review
body:
  - type: markdown
    attributes:
      value: |
        ## Report an Inactive Food Resource Location

        Thank you for helping maintain our community food resources database! Please provide details about the location that appears to be inactive or closed.

  - type: textarea
    id: location-json
    attributes:
      label: Existing Location JSON Data
      description: Paste the JSON data for the existing location from locations.json or the map details
      placeholder: |
        {
          "name": "Community Food Pantry",
          "address": "123 Main St, Newnan, GA 30263",
          "county": "Coweta",
          "type": "Food Bank",
          "description": "Open Tuesdays and Thursdays 9am-5pm",
          "active": true,
          "lat": 33.3807,
          "lng": -84.7997
        }
      render: json
    validations:
      required: true

  - type: textarea
    id: inactive-reason
    attributes:
      label: Reason for Inactivity
      description: Please explain why this location appears to be inactive
      placeholder: |
        - Closed permanently
        - Moved to a new location
        - No longer offering food assistance
        - Phone number disconnected
        - Website shows closed status
      render: markdown
    validations:
      required: true

  - type: input
    id: verification-source
    attributes:
      label: Verification Source
      description: How did you determine this location is inactive? (link, photo, phone call, etc.)
      placeholder: https://example.com or "Called phone number - disconnected"

  - type: input
    id: contact
    attributes:
      label: Contact Information (Optional)
      description: If you'd like to be contacted about this report, please provide your email or preferred contact method
      placeholder: email@example.com

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have attempted to verify this location is inactive through multiple sources
          required: true
        - label: This is not a temporary closure (holidays, renovations, etc.)
          required: false

  - type: markdown
    attributes:
      value: |
        ## For Maintainers

        After reviewing this report:
        - [ ] Verify the location is indeed inactive through additional sources
        - [ ] Update locations.json to set "active": false or remove the entry
        - [ ] Run `node pregeocode.js --write` if coordinates need updating
        - [ ] Test that the location no longer appears on the active map
        - [ ] Close this issue once resolved
